# Generated by Django 5.2.3 on 2025-08-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('personality', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('birthHouse', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=100)),
                ('hobby', models.CharField(blank=True, max_length=100)),
                ('landmarkItem', models.CharField(blank=True, max_length=100)),
                ('motivation', models.CharField(max_length=100)),
                ('history', models.TextField()),
            ],
        ),
    ]
