# Generated by Django 5.2.3 on 2025-08-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterMaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createCharacter',
            new_name='createCharacterModel',
        ),
    ]
