# Generated by Django 5.2.3 on 2025-08-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterMaker', '0002_rename_createcharacter_createcharactermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcharactermodel',
            old_name='birthHouse',
            new_name='birthPlace',
        ),
    ]
